version: "3.5"

services:
  testxdb_postgres:
    image: postgres:12
    hostname: testxdb_postgres
    environment:
      POSTGRES_PASSWORD: testxdb
      POSTGRES_USER: testxdb
      POSTGRES_DB: main

  testxdb:
    image: testxdb
    working_dir: /app/test_xdb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.bigquery/keyfile.json:/app/test_xdb/keyfile.json
    command: tail -f /dev/null
