version: "3.5"

services:
  testxdb_postgres:
    image: postgres:12
    hostname: testxdb_postgres
    environment:
      POSTGRES_PASSWORD: testxdb
      POSTGRES_USER: testxdb
      POSTGRES_DB: testxdb

  testxdb:
    image: testxdb
    working_dir: /app
    environment:
      PATH: "/app:${PATH}"
      SNOWFLAKE_USERNAME: "${DBT_XDB_SNOWFLAKE_USER}"
      SNOWFLAKE_PASSWORD: "${DBT_XDB_SNOWFLAKE_PASSWORD}"
      SNOWFLAKE_ACCOUNT: "${DBT_XDB_SNOWFLAKE_ACCOUNT}"
      SNOWFLAKE_DATABASE: "${DBT_XDB_SNOWFLAKE_DATABASE}"
      BIGQUERY_PROJECT: "${DBT_XDB_BIGQUERY_PROJECT}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test_xdb/:/app
      - ./:/dbt-xdb
    command: tail -f /dev/null  
