
version: 2

models:
    - name: regexp_test
      description: "tests regexp"
      columns:
          - name: banana_domain
            tests:
              - accepted_values:
                  values: ['https://www.banana.com/landing-page/subpage?query=thing', 'https://www.banana.com?query=thing']
          - name: landing_page_url
            tests:
              - accepted_values:
                  values: ['https://www.banana.com/landing-page/subpage?query=thing']
                  
    - name: any_value_test
      description: "tests returns any value"
      columns:
          - name: value_col
            tests:
              - not_null

    - name: using_test
      description: "tests using join clause"
      columns:
          - name: number_of_rows
            tests:
              - accepted_values:
                   values: [1]
                   quote: false

    - name: aggregate_strings_test
      description: "tests aggregate_strings macro"
      columns:
          - name: value_col
            tests: 
              - not_null
              - accepted_values:
                   values: ["apple,tractor,zebra"]
                   quote: true

    - name: datediff_test
      description: "tests datediff macro"
      columns:
          - name: one_day_diff
            tests:
              - not_null
              - accepted_values:
                   values: [1]
                   quote: false
          - name: two_week_diff
            tests:
              - not_null
              - accepted_values:
                   values: [2]
                   quote: false
          - name: three_month_diff
            tests:
              - not_null
              - accepted_values:
                   values: [3]
                   quote: false
          - name: four_year_diff
            tests:
              - not_null
              - accepted_values:
                   values: [4]
                   quote: false
          - name: five_quarter_diff
            tests:
              - not_null
              - accepted_values:
                   values: [5]
                   quote: false
    - name: dateadd_test
      description: "adds dates"
      columns:
          - name: one_day_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-02']
                   quote: true
          - name: one_day_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-31']
                   quote: true
          - name: one_week_added
            tests:
              - not_null
              - accepted_values:
                   values: ['2020-01-08']
                   quote: true
          - name: one_week_subtracted
            tests:
              - not_null
              - accepted_values:
                   values: ['2019-12-25']
                   quote: true
