
version: 2

models:
    - name: regexp
      description: "tests regexp"
      columns:
          - name: banana_domain
            tests:
              - accepted_values:
                  values: ['https://www.banana.com/landing-page/subpage?query=thing', 'https://www.banana.com?query=thing']
          - name: landing_page_url
            tests:
              - accepted_values:
                  values: ['https://www.banana.com/landing-page/subpage?query=thing']
                  
